### ISSUE TITLE
Strings containing token characters throws error

### ISSUE THREAD

**Issue by jordanbtucker** [neodon/json6#1]
```bash
node> json6('"("')
{ type: 'dqt', char: '"' }
accepted dqt
{ type: 'lpr', char: '(' }
Error: Unexpected type for token: dqt did not match {"type":"lpr","char":"("}
    at expect (D:\Users\Jordan\Desktop\json6-test\node_modules\json6\lib\index.js:109:11)
    at file (D:\Users\Jordan\Desktop\json6-test\node_modules\json6\lib\index.js:134:7)
    at parse (D:\Users\Jordan\Desktop\json6-test\node_modules\json6\lib\index.js:281:10)
    at module.exports (D:\Users\Jordan\Desktop\json6-test\node_modules\json6\lib\index.js:285:10)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:164:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:393:12)
    at emitOne (events.js:82:20)
```

**Comment by neodon** [comment]
Thanks Jordan, I will take a look at this.  Hoping to work on the code some more this weekend to get it into better shape.

**Comment by jordanbtucker** [comment]
It looks like the tokenizer is treating all non-token characters as `text ` and vice versa.

Are you planning on making this backward compatible with JSON? Are you planning on making this a subset of ES6? What about comments?
